FROM node:24-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build

FROM nginx:alpine 
# This replaces the default Nginx config inside the container.
COPY nginx.conf /etc/nginx/conf.d/default.conf
# copy static files from build stage to nginx html folder
COPY --from=build /usr/src/app/dist /usr/share/nginx/html